apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hive-managed-services
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hive-managed-services
    app.kubernetes.io/part-of: hive
  name: hive-managed-services
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: hive-managed-services
status:
  loadBalancer: {}
